services:
  - type: web
    name: resume-screening-ai
    env: python
    region: oregon
    plan: free
    buildCommand: cd resume_screening_api && pip install -r requirements.txt
    startCommand: cd resume_screening_api && gunicorn wsgi:app --bind 0.0.0.0:$PORT --workers 2 --timeout 120
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: MAX_CONTENT_LENGTH
        value: "16777216"
